import matplotlib.pyplot as plt

def plot_efficiency_vs_pressure_ratio(df):
    plt.figure(figsize=(8, 5))
    plt.plot(df["pressure_ratio"], df["thermal_efficiency"]*100, marker='o')
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Thermal Efficiency (%)")
    plt.title("Thermal Efficiency vs Pressure Ratio")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("Graphs/Efficiency_vs_Pressure_Ratio.png")
    plt.show()

def plot_efficiency_vs_net_work(df):
    plt.figure(figsize=(8, 5))
    plt.plot(df["W_net"], df["thermal_efficiency"]*100, marker='o')
    plt.xlabel("Net Work Output (W_net) (J/kg)")
    plt.ylabel("Thermal Efficiency (%)")
    plt.title("Thermal Efficiency vs Net Work Output")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("Graphs/Efficiency_vs_Net_Work.png")
    plt.show()

def plot_net_work_vs_pressure_ratio(df):
    plt.figure(figsize=(8, 5))
    plt.plot(df["pressure_ratio"], df["W_net"], marker='o')
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Net Work Output (W_net) (J/kg)")
    plt.title("Net Work Output vs Pressure Ratio")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("Graphs/Net_Work_vs_Pressure_Ratio.png")
    plt.show()

def plot_net_work_vs_pressure_ratio_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["W_net"], marker='o', label="Ideal Cycle")
    plt.plot(df_real["pressure_ratio"], df_real["W_net"], marker='x', label="Real Cycle")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Net Work Output (W_net) (J/kg)")
    plt.title("Net Work Output vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Net_Work_vs_Pressure_Ratio_Comparison.png")
    plt.show()

def plot_power_vs_pressure_ratio_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["power_net"]/1000, marker='o', label="Ideal Cycle")
    plt.plot(df_real["pressure_ratio"], df_real["power_net"]/1000, marker='x', label="Real Cycle")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Net Power Output (kW)")
    plt.title("Net Power Output vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Power_vs_Pressure_Ratio.png")
    plt.show()

def plot_net_power_vs_pressure_ratio_real_cpl_5(df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_real["pressure_ratio"], df_real["power_net"]/1000, marker='o', label="Real Cycle with Combustor Pressure Loss")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Net Power Output (kW)")
    plt.title("Net Power Output vs Pressure Ratio (Real Cycle with Combustor Pressure Loss)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Power_vs_Pressure_Ratio_Real_CPL.png")
    plt.show()

def plot_net_power_vs_pressure_ratio_real_cpl_0(df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_real["pressure_ratio"], df_real["power_net"]/1000, marker='o', label="Real Cycle with no Combustor Pressure Loss")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Net Power Output (kW)")
    plt.title("Net Power Output vs Pressure Ratio (Real Cycle with no Combustor Pressure Loss)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Power_vs_Pressure_Ratio_Real_No_CPL.png")
    plt.show()

def plot_efficiency_vs_pressure_ratio_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["thermal_efficiency"]*100, marker='o', label="Ideal Cycle")
    plt.plot(df_real["pressure_ratio"], df_real["thermal_efficiency"]*100, marker='x', label="Real Cycle")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Thermal Efficiency (%)")
    plt.title("Thermal Efficiency vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Efficiency_vs_Pressure_Ratio_Comparison.png")
    plt.show()

def plot_efficiency_vs_net_work_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["W_net"], df_ideal["thermal_efficiency"]*100, marker='o', label="Ideal Cycle")
    plt.plot(df_real["W_net"], df_real["thermal_efficiency"]*100, marker='x', label="Real Cycle")
    plt.xlabel("Net Work Output (W_net) (J/kg)")
    plt.ylabel("Thermal Efficiency (%)")
    plt.title("Thermal Efficiency vs Net Work Output (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Efficiency_vs_Net_Work_Comparison.png")
    plt.show()

def plot_exergy_destruction_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_destruction_compressor_specific"], marker='o', label="Compressor Exergy Destruction (Ideal Cycle)")
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_destruction_turbine_specific"], marker='o', label="Turbine Exergy Destruction (Ideal Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_destruction_compressor_specific"], marker='x', label="Compressor Exergy Destruction (Real Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_destruction_turbine_specific"], marker='x', label="Turbine Exergy Destruction (Real Cycle)")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Specific Exergy Destruction (J/kg)")
    plt.title("Specific Exergy Destruction vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Exergy_Destruction_vs_Pressure_Ratio_Comparison.png")
    plt.show()

def plot_second_law_efficiency_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["second_law_efficiency"]*100, marker='o', label="Ideal Cycle")
    plt.plot(df_real["pressure_ratio"], df_real["second_law_efficiency"]*100, marker='x', label="Real Cycle")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Second Law Efficiency (%)")
    plt.title("Second Law Efficiency vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Second_Law_Efficiency_vs_Pressure_Ratio_Comparison.png")
    plt.show()

def plot_specific_exergy_destruction_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_specific_destruction_total"], marker='o', label="Total Specific Exergy Destruction (Ideal Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_specific_destruction_total"], marker='x', label="Total Specific Exergy Destruction (Real Cycle)")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Total Specific Exergy Destruction (J/kg)")
    plt.title("Total Specific Exergy Destruction vs Pressure Ratio (Ideal vs Real)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Specific_Exergy_Destruction_vs_Pressure_Ratio_Comparison.png")
    plt.show()

def plot_LossBreakdown_comparison(df_ideal, df_real):
    plt.figure(figsize=(8, 5))
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_destruction_compressor_specific"], marker='o', label="Compressor Exergy Destruction (Ideal Cycle)")
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_destruction_turbine_specific"], marker='o', label="Turbine Exergy Destruction (Ideal Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_destruction_compressor_specific"], marker='x', label="Compressor Exergy Destruction (Real Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_destruction_turbine_specific"], marker='x', label="Turbine Exergy Destruction (Real Cycle)")
    plt.plot(df_ideal["pressure_ratio"], df_ideal["exergy_specific_destruction_total"], marker='+', label="Total Exergy Destruction (Ideal Cycle)")
    plt.plot(df_real["pressure_ratio"], df_real["exergy_specific_destruction_total"], marker='+', label="Total Exergy Destruction (Real Cycle)")
    plt.xlabel("Pressure Ratio")
    plt.ylabel("Specific Exergy Destruction (J/kg)")
    plt.title("Specific Exergy Destruction vs Pressure Ratio (Ideal vs Real vs Total)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig("Graphs/Loss_Breakdown_vs_Pressure_Ratio_Comparison.png")
    plt.show()